language: python
python:
    - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

install:
    - pip install -U platformio
    - pio update

script:
    - pio run

deploy:
  provider: releases
  api_key:
    secure: UrEjFMZM9QBcXL6jNEPgpJygr0FGsO0cEBQyzrjrH1oyLhKm4wctbvjksyw7irgTQkFY6ydlKitDqb+IXQbvHFD2AYIr+NiiV/hBA2eRkRwwch1ZJOvEGT+7ThEcgIy+uO3KKh8DICvQ/kzeCHGLKcrfMFKtG388NYzV5AzH0I+MTuJulPD1dKynx/YqAcKqEMSzPYZWh82tT1P0SWebx8wTvxQ+JojmaEfpZqSdMy4aGBZX6ijdLnbe6SxKc73bo3xdvtC5zsNvxyBcSTJ8Zc6SlispLK/YsdD+Qa/OGZgQcYGiVV1UiDjVRvdhBWKdz2l/Vy/HHE+a0Q02jgePr+lFDy2TcLaQEYd07QQnDJnYFj8eFBoK8Oeg4IbIxoMfp1zvGbjXPO/5HdNhxgE6GiGGF3sI1ieVIU9taBfwS4vUC+v1N6WZGQ24GWLfLvOmIvhPJshapwubZmwoXqLgFhuwHyoBMCN2iJCdtLTBphNMOHwHs7+nHPpwcRNvRDytI0ETLZahPCHxC+/Pyg7jRVqhmn2VmSkXiBlmHfKIqOOp4pRjoqM6g6fICGlQPUnReH8ERMb18WCxxN8FsC9SkGTmaKCqFQHV2+113LU+fw/+HNUa7anFMD0/cy80WnbTIQ2FMt0tvZQ23/VVr1ztOnuCT7pRnMEjl9+jKdnrDm0=
  file:
    - .pio/build/d1_mini_pro/firmware.bin
  skip_cleanup: true
  on:
    repo: bertbaron/git_ota_update
    tags: true